# Generated by Django 4.0.6 on 2022-10-15 16:59

from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20220724_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[users.validators.UsernameValidator('me')]),
        ),
    ]
